
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sales
 */
public class ControleReservas extends javax.swing.JFrame {

    private String id;

    /**
     * Creates new form ControleReservas
     */
    public ControleReservas() {
        initComponents();
    }
    
     public ControleReservas(String id) {
        this.id = id;
         initComponents();
        // Carrega os dados recebidos nos campo da tela
        txtMesas.setText(id);
        txtMesas.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPessoas = new javax.swing.JTextField();
        txtHorario = new javax.swing.JTextField();
        txtMesas = new javax.swing.JTextField();
        btnReserva = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservas");
        setBackground(new java.awt.Color(160, 15, 45));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Reservas ------- Faça sua reserva agora ou por telefone: 94002-8922");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 16);

        jLabel2.setText("N° Pessoas:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 170, 70, 30);

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 50, 30);

        jLabel4.setText("Horário:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 50, 30);

        txtPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPessoasActionPerformed(evt);
            }
        });
        getContentPane().add(txtPessoas);
        txtPessoas.setBounds(100, 170, 150, 30);
        getContentPane().add(txtHorario);
        txtHorario.setBounds(100, 130, 150, 30);
        getContentPane().add(txtMesas);
        txtMesas.setBounds(100, 40, 150, 30);

        btnReserva.setText("Fazer Reserva");
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });
        getContentPane().add(btnReserva);
        btnReserva.setBounds(170, 220, 130, 30);

        jLabel5.setText("Mesa:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 50, 50, 16);
        getContentPane().add(txtNome);
        txtNome.setBounds(100, 90, 150, 30);

        setSize(new java.awt.Dimension(545, 288));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPessoasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPessoasActionPerformed

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed

// 1- Pegar os dados dos campos
        String n, h, p;
        n = txtNome.getText();
        h = txtHorario.getText();
        p = txtPessoas.getText().toString();
        try {
            // 2- Conectar com o BD
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante", "root", "");
            // 3- Pegar os dados alterados e devolver para a tabela do BD
            var st = conectar.prepareStatement("INSERT INTO reservas (nome, horario, npessoas, idmesa) VALUES (?, ?, ?, ?)");
            st.setString(1, n);
            st.setString(2, h);
            st.setString(3, p);
            st.setString(4, id);
            st.executeUpdate(); // executa a alteraçao (UPDATE)
            JOptionPane.showMessageDialog(null,"Reserva Concluida");
            dispose(); // fecha a tela
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null,"Entre em contato com o suporte e informe o erro:" + ex.getMessage());
        }
            
    }//GEN-LAST:event_btnReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtMesas;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPessoas;
    // End of variables declaration//GEN-END:variables
}
