
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sales
 */
public class ControleMesas extends javax.swing.JFrame {

    /**
     * Creates new form ControleMesas
     */
    public ControleMesas() {
        initComponents();
        controleMesas();
    }
    
    public void controleMesas() {
        try {
            // 1- Conexão com o BD
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante","root","");
            // 2- Buscar todos os dados que eu quero exibir na tela
            var st = conectar.prepareStatement("SELECT mesas.idmesa, reservas.nome \n" +"FROM mesas \n" +"LEFT JOIN reservas ON mesas.idmesa = reservas.idmesa");
            ResultSet mesas = st.executeQuery(); // essa linha executa o SELECT
            DefaultTableModel tblModelo = (DefaultTableModel) tblMesas.getModel();
            tblModelo.setRowCount(0);
            // passa linha por linha até o final da tabela
            while(mesas.next()){
                String linha[]={
                    mesas.getString("idmesa"),
                    mesas.getString("nome"),
                };
                tblModelo.addRow(linha);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null,"Entre em contato com o suporte e informe o erro:" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtMesas = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMesas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle Mesas");
        getContentPane().setLayout(null);

        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Confirma Mesa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 10, 130, 30);

        txtMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesasActionPerformed(evt);
            }
        });
        getContentPane().add(txtMesas);
        txtMesas.setBounds(390, 10, 110, 30);

        tblMesas.setForeground(new java.awt.Color(153, 0, 0));
        tblMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Mesas", "Reservada"
            }
        ));
        jScrollPane2.setViewportView(tblMesas);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 60, 390, 180);

        setSize(new java.awt.Dimension(533, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1- Obter o nome do item a ser alterado
        String i;
        i = txtMesas.getText().toString();
        try {
    // 2- Conectar com o DB restaurante
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante", "root", "");

    // 3- Verificar se o idmesa já está cadastrado na tabela reservas
    var st = conectar.prepareStatement("SELECT idmesa FROM reservas WHERE idmesa = ?");
    st.setString(1, i);
    ResultSet rs = st.executeQuery(); // executa o comando SELECT

    // 4- Se o idmesa não estiver cadastrado, inserir na tabela reservas
    if (rs.next()) {
        JOptionPane.showMessageDialog(null, "Mesa já está reservada");
    } else {
        // Inserir o idmesa na tabela reservas
        var su = conectar.prepareStatement("INSERT INTO reservas (idmesa) VALUES (?)");
        su.setString(1, i);
        // 5- Passar o idmesa para a outra tela
        new ControleReservas(i).setVisible(true);
        dispose(); 
    }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null,"Entre em contato com o suporte e informe o erro:" + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleMesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMesas;
    private javax.swing.JTextField txtMesas;
    // End of variables declaration//GEN-END:variables
}
