
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sales
 */
public class Funcionarios extends javax.swing.JFrame {

    /**
     * Creates new form Funcionarios
     */
    public Funcionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        itmAlterarEstoque = new javax.swing.JMenuItem();
        itmBuscar = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tendencias-de-restaurantes-1024x682.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-40, -50, 610, 310);

        jMenu1.setText("Garçon");

        jMenuItem1.setText("Iniciar pedido");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Enviar para cozinha");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Retirar da cozinha");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Fechar pedido");
        jMenu1.add(jMenuItem4);

        jMenuItem6.setText("Reservas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Listar Reservas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cozinha");

        jMenuItem10.setText("Listar pedido");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Etregar pedido");
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Estoque");

        jMenuItem5.setText("Cadastrar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        itmAlterarEstoque.setText("Alterar");
        itmAlterarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarEstoqueActionPerformed(evt);
            }
        });
        jMenu3.add(itmAlterarEstoque);

        itmBuscar.setText("Buscar");
        itmBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarActionPerformed(evt);
            }
        });
        jMenu3.add(itmBuscar);

        jMenuItem8.setText("Excluir");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Listar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Ajuda");
        jMenuBar1.add(jMenu5);

        jMenu4.setText("Sair");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(625, 341));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        new CadastrarEstoque().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        String id;
        id = JOptionPane.showInputDialog(null,"Informe o ID do Item a ser excluido");
        try {
            // 2- Conectar ao BD
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante","root","");
            // 3- Excluir o Item informado
           var st = conectar.prepareStatement("DELETE FROM estoque WHERE idproduto= ?");
            st.setString(1, id);
            int retorno = st.executeUpdate();
            if (retorno == 1)
            JOptionPane.showMessageDialog(null,"Item excluido com sucesso");
            else
                JOptionPane.showMessageDialog(null,"Item não encontrado");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Entre em contato com o suporte e informe o erro:" + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Entre em contato com o suporte e informe o erro:" + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new ListarEstoque().setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void itmAlterarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarEstoqueActionPerformed

        // 1- Obter o nome do item a ser alterado
        String i;
        i = JOptionPane.showInputDialog("ID do item a ser alterado:");
        try {
            // 2- Conectar com o DB restaurante
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante","root","");
            // 3- Buscar o item na tabela do BD
            var st = conectar.prepareStatement("SELECT * FROM estoque WHERE idproduto = ?");
            st.setString(1, i);
            ResultSet idproduto = st.executeQuery(); // executa o comando SELECT
            // 4- Verificar se encontrou o item na tabela do BD
            if(idproduto.next()){ // se encontrou ?
                // 5- Enviar os dados do item para a tela AlterarEstoque
                String idp,ite,qtd,der;
                idp = idproduto.getString("idproduto");
                ite = idproduto.getString("item");
                qtd = idproduto.getString("quantidade");
                der = idproduto.getString("departamento");
                new AlterarEstoque(idp,ite,qtd,der).setVisible(true);
            }else{ 
                JOptionPane.showMessageDialog(null,"Item não encontrado");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null,"Entre em contato com o suporte e informe o erro:" + ex.getMessage());
        }
    }//GEN-LAST:event_itmAlterarEstoqueActionPerformed

    private void itmBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarActionPerformed
         // 1- Obter o nome do item a ser alterado
        String i;
        i = JOptionPane.showInputDialog("ID do Item a ser buscado:");
        try {
            // 2- Conectar com o DB restaurante
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante","root","");
            // 3- Buscar o item na tabela do BD
            var st = conectar.prepareStatement("SELECT * FROM estoque  WHERE idproduto = ?");
            st.setString(1, i);
            ResultSet idproduto = st.executeQuery(); // executa o comando SELECT
            // 4- Verificar se encontrou o item na tabela do BD
            if(idproduto.next()){ // se encontrou ?
                // 5- Enviar os dados do item para a tela AlterarEstoque
                String ite,qtd,der;
                ite = idproduto.getString("item");
                qtd = idproduto.getString("quantidade");
                der = idproduto.getString("departamento");
               JOptionPane.showMessageDialog(null,
                       "Item:" + ite + "\n" +
                       "Quantidade:" + qtd + "\n" +
                       "Departamento:" + der 
               );
            }else{ 
                JOptionPane.showMessageDialog(null,"Item não encontrado");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null,"Entre em contato com o suporte e informe o erro:" + ex.getMessage());
        }
        
    }//GEN-LAST:event_itmBuscarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new ControleMesas().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new ListarReservas().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterarEstoque;
    private javax.swing.JMenuItem itmBuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
